# Generated by Django 5.2.1 on 2025-05-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='Idclientes', primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=45, unique=True)),
                ('nombre_cliente', models.CharField(db_column='nombredelcliente', max_length=45)),
                ('direccion_envio', models.CharField(blank=True, db_column='direccion_de_envio', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('clientescol', models.CharField(blank=True, max_length=45, null=True)),
                ('telefonocol', models.CharField(blank=True, max_length=45, null=True)),
                ('clientescol1', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('imagen', models.CharField(blank=True, db_column='imagen', max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='tienda_app.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='Idcliente_pedido', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('direccion_envio', models.CharField(blank=True, db_column='direccion_envio', max_length=255, null=True)),
                ('fecha_pedido', models.DateTimeField(blank=True, db_column='fechapedido', null=True)),
                ('pedidoscol', models.CharField(blank=True, max_length=45, null=True)),
                ('cliente', models.ForeignKey(db_column='clientes_idclientes', on_delete=django.db.models.deletion.CASCADE, to='tienda_app.cliente')),
                ('producto', models.ForeignKey(db_column='productos_ID_INT', on_delete=django.db.models.deletion.CASCADE, to='tienda_app.producto')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, db_column='fechaAgregado')),
                ('cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='tienda_app.cliente')),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='tienda_app.producto')),
            ],
            options={
                'db_table': 'carrito',
                'unique_together': {('producto', 'cliente')},
            },
        ),
    ]
