# Generated by Django 5.2.1 on 2025-05-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_producto_stock_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
